@baseUrl=http://localhost:3000
@accessTokenName=access-token
@accessToken=
@refreshTokenName=
@refreshToken=

### 회원가입
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "email": "test@test.com",
    "nickname": "tester",
    "password": "password"
}

### 로그인
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### 로그아웃
POST {{baseUrl}}/users/logout
Cookie: {{accessTokenName}}={{accessToken}}

### 상품 등록
POST {{baseUrl}}/products
Cookie: {{accessTokenName}}={{accessToken}}

{
    "name":"Test_Product",
    "description":"Test_Description",
    "price":"10000",
    "tags":[]
}

### 게시글 등록